### ISSUE TITLE
VirtualBox GUI has Changed - No Host-Only-Network tab

### ISSUE THREAD

**Issue by royobrecht** [jaredhaight/articles#2]
The "Host Only" tab does not exist in VirtualBox Preferences as directed in Part-1. I'm running the latest stable release: Version 5.2.2 r119230 (Qt5.6.2) which changed since this guide was created.

Screenshot of Preferences window without Host Only tab.

![2017-12-03 18_54_49-virtualbox - preferences](https://user-images.githubusercontent.com/7474477/33535566-30b4f6cc-d863-11e7-9c2c-f92164bc34c8.png)

There are likely other changes to GUI that no longer match this guide.

**Comment by jaredhaight** [comment]
Articles have been updated. Thanks for the heads up!
